version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.17
    container_name: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - mynetwork
      - fleet-external
  go:
    container_name: go
    build:
      context: ./go
      dockerfile: Dockerfile
    # ports:
    #   - "3333:3333"
    #   - "4444:4444"
    networks:
      - mynetwork
      - fleet-external

networks:
  mynetwork:
      driver: bridge
  fleet-external:
    external: true