version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./404.html:/var/www/binaryville/404.html
      - ./admin.html:/var/www/binaryville/admin.html
      - ./index.html:/var/www/binaryville/index.html
      - ./binaryville.conf:/etc/nginx/conf.d/binaryville.conf
    secrets:
      - nginx_key
      - nginx_crt
    depends_on:
      - python_server

  python_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_server
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
    restart: always

secrets:
  nginx_key:
    file: .certs/nginx.key
  nginx_crt:
    file: .certs/nginx.crt
