---
- name: Deploying Nginx website
  hosts: all
  become: yes
  vars:
    user: "ubuntu"

  tasks:
    - name: Create directory with parent directories
      ansible.builtin.file:
        path: /var/www/myserver
        state: directory
        mode: "0755"

    - name: Copy app files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/myserver
        owner: "{{ user }}"
        group: root
        mode: "0644"
      with_fileglob:
        - "../../app/*.js"
        - "../../app/*.json"

    - name: Start the app
      ansible.builtin.shell: >
        nohup node /var/www/myserver/server.js > /var/www/myserver/app.log 2>&1 &

    - name: Ensure that app is running
      shell: ps aux | grep node
      register: app_status
    - debug:
        msg: "{{app_status.stdout_lines}}"
