# Used modules below...
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
---
- name: Provision EC2 with bare-minimum packages and install Nginx
  hosts: all
  gather_facts: false
  connection: ssh
  become: yes
  tasks:
    - name: Populate Apt's Cache with package definitions to avoid "no such package" errors
      ansible.builtin.apt:
        update_cache: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip

    - name: Ensure botocore and boto3 modules are installed
      ansible.builtin.pip:
        name: ["boto3", "botocore"]
        extra_args: "--user"

    - name: Update the repository cache and update package "nginx" to latest version
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
