---
- name: Deploying Nginx website
  hosts: all
  become: yes
  vars:
    user: "ubuntu"

  tasks:
    - name: Create directory with parent directories
      ansible.builtin.file:
        path: /var/www/s3
        state: directory

    - name: Copy all files from the local directory
      ansible.builtin.copy:
        src: ../files/
        dest: /var/www/s3/
        owner: "{{ user }}"
        group: root
        mode: "0644"
